{
 "title": "AskSin VM",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "HmIPDevices",
    "label": "HmIP-Devices",
    "query": {
     "query": "label_values(Telegrams_dc, fromName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device DutyCycle",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (fromName) (avg_over_time(Telegrams_dc[$__range]))",
     "legendFormat": "{{fromName}}"
    }
   ]
  },
  {
   "title": "Device Telegram count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (fromName) (count_over_time(Telegrams_rssi[$__range]))",
     "legendFormat": "{{fromName}}"
    }
   ]
  },
  {
   "title": "Device DutyCycle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (fromName) (avg_over_time(Telegrams_dc{fromName=~\"$HmIPDevices\"}[$__interval]))",
     "legendFormat": "{{fromName}}"
    }
   ]
  },
  {
   "title": "Telegram count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "running_sum(sum by (fromName) (count_over_time(Telegrams_rssi{fromName=~\"$HmIPDevices\"}[$__interval])))",
     "legendFormat": "{{fromName}}"
    }
   ]
  }
 ]
}