{
 "title": "AskSin",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "HmIPDevices",
    "label": "HmIP-Devices",
    "query": "import \"influxdata/influxdb/schema\"\r\n \r\nschema.tagValues(\r\n  bucket: \"AskSinAnalyzer\",\r\n  tag: \"fromName\",\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "RaspberryMatic Duty Cycle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CCU3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CCU3_DutyCycle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device DutyCycle",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AskSinAnalyzer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Telegrams\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dc\")\r\n  |> group(columns: [\"fromName\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Device Telegram count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AskSinAnalyzer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Telegrams\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cnt\")\r\n  |> group(columns: [\"fromName\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Device DutyCycle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"AskSinAnalyzer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Telegrams\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dc\")\r\n  |> filter(fn: (r) => r[\"fromName\"] =~ /^${HmIPDevices:regex}/)\r\n  |> group(columns: [\"fromName\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Telegram count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"AskSinAnalyzer\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Telegrams\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cnt\")\r\n  |> filter(fn: (r) => r[\"fromName\"] =~ /^${HmIPDevices:regex}/)\r\n  |> group(columns: [\"fromName\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> cumulativeSum()\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  }
 ]
}